version: '3.7'

services:
  main:
    container_name: nest-docker
    image: truongvn/trello-nestjs:latest
#    build:
#      context: .
#      target: production
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}

    env_file:
      - .env
    depends_on:
      - redis
      - database
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - '.:/var/lib/redis'
  database:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - '.:/var/lib/mongo:rw'
#networks:
#  web-nest:
